### ISSUE TITLE
Low resolution texture paint

### ISSUE THREAD

**Issue by lucasthomaz97** [spimort/TerraBrush#145]
![image](https://github.com/user-attachments/assets/73339930-33a1-4fd8-a018-1fbb5e692748)

i'm making a proof of concept of my game graphics, i'm using clear colors since my game is going towards a cel-shaded art style.
i'm setting the textures as gradient textures 1d with 1px width, just to handpaint a color, but it's getting this darken transition between the colors and it's pretty pixelated, how can i pass through it?
I'm also using a really simple custom shader that just adds fresnel effect and cartoon lightning to the terrain.
Can i raise the resolution of this texture? Can i get rid of this filtering in any configuration of the addon?

**Comment by spimort** [comment]
Not "built in" but there are ways!
With a custom shader, what you could do is to change the filter on the splatmaps : 

For example, this is the regular Terrain : 
![image](https://github.com/user-attachments/assets/755cdcb5-be52-4226-9dde-273b993afdf5)

If I change the filter on the splatmaps : 
![image](https://github.com/user-attachments/assets/7dbc7827-6c48-42c1-8d6d-d9788e4dbfdd)

Your custom shader should be based on the file "heightmap_clipmap_shader_include.gdshaderinc".

Instead of having this : 
```glsl
uniform sampler2DArray Splatmaps : repeat_disable;
```
It should be like this : 
```glsl
uniform sampler2DArray Splatmaps : repeat_disable, filter_nearest_mipmap;
```

Let me know if this helps!

**Comment by lucasthomaz97** [comment]
well, it helps, but not fully. the filter is gone, but the texture is too pixelated, how can i raise only the albedo texture resolution?
![image](https://github.com/user-attachments/assets/13360cf7-168b-40f5-b724-cc78654bf85a)

**Comment by spimort** [comment]
It's because when you paint, the brush has transparency. If you hold the paint brush for a longer time, it will fill out the transparent blocks.

You could use this brush which does not really have transparency : 
![image](https://github.com/user-attachments/assets/4b5424d6-9acb-4d0d-b359-c0ff48a0e49d)

If needed, you can create custom brushes. You can configure the custom brushes folder here : 
![image](https://github.com/user-attachments/assets/3798e3bb-4101-4ecd-9b6a-a39b86560647)

Let me know if this helps!

**Comment by lucasthomaz97** [comment]
![image](https://github.com/user-attachments/assets/275451ac-e8e5-472a-be34-f3cbc02c54ff)
By using the square brush it really made the color merge disapear, but it keeps being pixelated as you can notice in this print.
is there anywhere in code i can raise the resolution?

**Comment by spimort** [comment]
I just realized what you meant by raising the resolution, my bad! 
But no, sadly, right now the splatmaps are 1px per meter, it's not possible to change the resolution right now 🫤

It would not be impossible to add, but it would requires some changes that's for sure.

**Comment by lucasthomaz97** [comment]
Ok, thanks.

**Comment by spimort** [comment]
I think for now, we can close the issue right?
You can always open a dedicated one for terrain resolution if this is something you really need (it does not mean we'll do it but we will have it logged)! 🙂

**Comment by lucasthomaz97** [comment]
Where in the code you set the resolution?

**Comment by spimort** [comment]
In the file `ZoneUtils.cs`, the size of the image is being decided with the size of the zones.
For example, the function `CreateSplatmapImage` create an image the size of each zones (so 1px = 1meter).

But that's half of the problem because we also need to make sure that we can paint on each pixels if we change the resolution.
And that the shaders works fine as well.

**Comment by lucasthomaz97** [comment]
Ok, i'll check it
