### ISSUE TITLE
Allow for ORMMaterial3D and StandardMaterial3D

### ISSUE THREAD

**Issue by eumario** [spimort/TerraBrush#2]
Allow for ORMMaterial3D and StandardMaterial3D to be assigned to the TextureSetResource, or importable to it.

**Comment by spimort** [comment]
I'll check what I can do about this.

**Comment by spimort** [comment]
@jackhric , sounds good.
I'm in a big modification right now, but I'll def. check what I can do

**Comment by spimort** [comment]
@jackhric just to make sure, what were the expectation for this one? Having the whole standard material working with the terrain would be hard because there are a lot of parameters when using that kind of material.

I already talked with @eumario and he told me that for him, it was mostly to use the Albedo, normal, roughness and height of the material but nothing more. Is this something similar you were expecting? If so, it means that all the other parameters would be ignored.

**Comment by spimort** [comment]
I'll close this issue for now, but feel free to reopen it if this is still something you need
